const FILES = [
{
  name:"下料机器臂/Main.py",
  desc:"TCP服务端·8081·最先启动",
  sections:[
    { id:"xl_0", name:"连接初始化", lines:[
      {c:"# 导入必要的库"},
      {c:"import os"},
      {c:"import sys"},
      {c:"import socket"},
      {c:"from threading import Thread"},
      {c:"import time"},
      {c:"import DobotDllType as dType"},
      {c:"import re"},
      {c:""},
      {c:"# 加载机械臂动态链接库DobotDll.dll"},
      {c:"api = dType.load()"},
      {c:""},
      {c:"# 连接机械臂"},
      {c:"# ConnectDobot函数返回一个元组，第一个元素是连接状态码"},
      {c:"# 状态码：0-已连接，1-未找到设备，2-端口占用"},
      {c:"# 连接到COM端口，波特率115200"},
      {c:"state = dType.ConnectDobot(api, \"COM6\", 115200)[0]"},
      {c:""},
      {c:"# 打印机械臂连接状态"},
      {c:"# 使用状态码作为索引，从状态描述列表中获取对应文本"},
      {c:"print(\"连接状态:\", [\"已连接\", \"未找到设备\", \"端口占用\"][state])"},
      {c:""},
      {c:"# 设置机械臂PTP运动模式参数(门型运动时抬升高度为100,最大高度为110)"},
      {c:"dType.ClearAllAlarmsState(api)  # 清除所有警报状态"},
      {c:"dType.SetPTPJumpParams(api, 100, 110, isQueued=1)  # 设置跳跃运动参数"},
      {c:"dType.{{SetInfraredSensor}}(api, 1, {{2}}, version=1)  # 设置光电传感器，端口1，版本2",tip:"光电传感器 下料=2 上料=1",why:"第3参是端口号，下料机接2号、上料机接1号，记反了读不到料。"},
      {c:""},
      {c:"# 设置机械臂末端为夹爪"},
      {c:"# 参数：夹爪长度59.7mm，末端类型为夹爪"},
      {c:"dType.SetEndEffectorParams(api, 59.7, 0, 0, 1)"},
      {c:""},
      {c:"# api清空机械臂的指令队列"},
      {c:"dType.SetQueuedCmdClear(api)"},
      {c:""},
      {c:"# 开始执行队列指令"},
      {c:"dType.SetQueuedCmdStartExec(api)"},
      {c:""},
      {c:"# 设置末端夹爪状态"},
      {c:"# 参数：启用夹爪(1)，夹爪打开(0)"},
      {c:"dType.{{SetEndEffectorGripper}}(api, 0, 0, isQueued=1)",tip:"夹爪控制(开/合)",why:"第2参=使能,第3参=开合。现场骨架开头那行常被漏，要补回。"},
      {c:""},
      {c:"# 机械臂回零"},
      {c:"dType.SetHOMECmd(api, 1, isQueued=1)"},
    ]},
    { id:"xl_1", name:"坐标与码垛数据", lines:[
      {c:""},
      {c:"# 定义关键位置坐标"},
      {c:"P1 = [-76.6124,233.7214,108.1663,102.0224]  # 拍照点"},
      {c:""},
      {c:"# P4 = []  # 视觉标定点"},
      {c:""},
      {c:"P5 = [250, 0, 50, 0]  # 零点"},
      {c:"P6 = [-79.4929,278.4865,-3.6015,102.0224]  # 抓取点"},
      {c:""},
      {c:"# 定义4个种类物品的放置位置"},
      {c:"# P3是一个三维列表："},
      {c:"# 第一维：4个不同的物品种类"},
      {c:"# 第二维：每个种类有2个放置点（对应不同的垛）"},
      {c:"# 第三维：每个放置点的坐标[x, y, z, r]"},
      {c:"P3 = ["},
      {c:"    [  # 种类1"},
      {c:"        [193.7174, 196.4782, -63.6996, -11.1977],  # 1垛"},
      {c:"        [214.8398, 137.5126, 0, -25.7088]  # 2垛"},
      {c:"    ],"},
      {c:"    [  # 种类2"},
      {c:"        [275.9170, -0.9370, -64.8519, -56.7977],"},
      {c:"        [233.4059, -52.1135, 0, -69.3046]"},
      {c:"    ],"},
      {c:"    [  # 种类3"},
      {c:"        [200.4951, -189.5624, -66.9641, -99.9976],"},
      {c:"        [216.5076, -192.4751, 0, -114.8311]"},
      {c:"    ],"},
      {c:"    [  # 种类4"},
      {c:"        [8.1148, -275.8029, -66.6523, -144.9178],"},
      {c:"        [18.9142, -292.0411, 0, -161.7859]"},
      {c:"    ],"},
      {c:"]"},
      {c:""},
      {c:"# 记录每个种类物品已放置的数量"},
      {c:"add_up = [0, 0, 0, 0]"},
      {c:""},
      {c:"# 定义4个物品种类的名称"},
      {c:"# 可以根据需要切换不同的命名"},
      {c:"sampleClss=['1.jqr', '2.jxb','3.plc','4.sjxt']"},
    ]},
    { id:"xl_2", name:"线程函数(视觉/分类/上料/语音)", lines:[
      {c:"# sampleClss=['广东省', '浙江省','山东省','四川省']"},
      {c:"#sampleClss = ['1', '2', '3', '4']"},
      {c:""},
      {c:"def vision(socket, name):"},
      {c:"    \"\"\"处理视觉系统的通信线程函数\"\"\""},
      {c:"    while True:"},
      {c:"        # 接收视觉系统发送的数据"},
      {c:"        data = socket.{{recv}}(1024).{{decode}}('utf-8')",tip:"接收数据",why:"recv(1024)收最多1024字节,要.decode转字符串才能比较。"},
      {c:"        print(f\"{name}发送{data}\")"},
      {c:""},
      {c:"        # 如果数据包含\"M\"，是二维码数据，转发给分类系统"},
      {c:"        if \"M\" in data:",tip:"编号标志",why:"视觉识别出二维码后发以M开头的编号,分类端收到才开始识别。"},
      {c:"            M_number=data"},
      {c:"            tcpCliSock3.{{send}}(\"OK\".{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:"        elif \"OK\" in data:"},
      {c:"            time.sleep(3)"},
      {c:"            tcpCliSock2.{{send}}(M_number.{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:"        # 否则，向视觉系统发送拍照指令"},
      {c:"        elif data ==\"GP2NG\":"},
      {c:"            tcpCliSock1.{{send}}(\"getphoto2\".{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:"            time.sleep(1)  #分开发送"},
      {c:"        elif data ==\"GP1NG\":"},
      {c:"            tcpCliSock1.{{send}}(\"getphoto1\".{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:"            time.sleep(1)  # 等待1秒，让视觉系统处理"},
      {c:""},
      {c:""},
      {c:"        data = ''  # 清空数据"},
      {c:"        time.sleep(0.5)  # 短暂等待"},
      {c:""},
      {c:"def classification(socket, name):"},
      {c:"    \"\"\"处理分类系统的通信线程函数\"\"\""},
      {c:"    while True:"},
      {c:"        # 接收分类系统发送的数据"},
      {c:"        data = socket.{{recv}}(1024).{{decode}}('utf-8')",tip:"接收数据",why:"recv(1024)收最多1024字节,要.decode转字符串才能比较。"},
      {c:"        print(f\"{name}发送{data}\")"},
      {c:""},
      {c:"        # 获取物品在分类列表中的索引"},
      {c:"        index = sampleClss.index(str(data))"},
      {c:""},
      {c:"        # 移动到抓取点"},
      {c:"        move(P6[0], P6[1], P6[2], P6[3], 0, 1, 1)"},
      {c:""},
      {c:""},
      {c:""},
      {c:"        # 计算放置在哪一垛：0表示第一垛，1表示第二垛"},
      {c:"        # 当已放置数量为0或1时，放在第一垛；当已放置数量为2或3时，放在第二垛"},
      {c:"        k = 0 if add_up[index] < 2 else 1"},
      {c:""},
      {c:""},
      {c:""},
      {c:"        # 计算放置高度偏移：0表示底层，1表示上层"},
      {c:"        # 当已放置数量为偶数时放在底层，奇数时放在上层"},
      {c:"        j = add_up[index] % 2"},
      {c:""},
      {c:"        # 计算最终放置点坐标"},
      {c:"        delta_z = j * 10"},
      {c:"        x = (int)(P3[index][k][0])"},
      {c:"        y = (int)(P3[index][k][1])"},
      {c:"        z = (int)(P3[index][k][2] + delta_z)"},
      {c:"        r = (int)(P3[index][k][3])"},
      {c:""},
      {c:"        print(f\"放置点:{x}, {y}, {z}, {r}\")"},
      {c:""},
      {c:"        # 增加该种类物品计数"},
      {c:"        add_up[index] += 1"},
      {c:""},
      {c:"        # 移动到放置点上方"},
      {c:"        dType.{{SetPTPCmdEx}}(api, 1, x, y, 100, r, isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"        # 下降到放置点"},
      {c:"        move(x, y, z, r, 1, 0, 0)"},
      {c:"        # 抬起"},
      {c:"        dType.{{SetPTPCmdEx}}(api, 1, x, y, 100, r, isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:""},
      {c:"        # 检查是否所有物品都已放置（总共8个）"},
      {c:"        sum_add = sum(add_up)"},
      {c:"        if sum_add < 8:"},
      {c:"            # 通知上料系统和分类系统继续运行"},
      {c:"            tcpCliSock3.{{send}}({{\"run\"}}.{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:"            tcpCliSock2.{{send}}({{\"run\"}}.{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:""},
      {c:"        # 回到拍照点"},
      {c:"        dType.{{SetPTPCmdEx}}(api, 1, P1[0], P1[1], P1[2], P1[3], isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:""},
      {c:"def load_material(socket, name):"},
      {c:"    \"\"\"处理上料系统的通信线程函数\"\"\""},
      {c:"    while True:"},
      {c:"        # 接收上料系统发送的数据"},
      {c:"        data = socket.{{recv}}(1024).{{decode}}('utf-8')",tip:"接收数据",why:"recv(1024)收最多1024字节,要.decode转字符串才能比较。"},
      {c:"        print(f\"{name}发送{data}\")"},
      {c:""},
      {c:"        # 如果接收到物料到达信号"},
      {c:"        if data == 'arrive1':"},
      {c:"            # 通知视觉系统拍照"},
      {c:"            tcpCliSock1.{{send}}(\"getphoto1\".{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:"        if data == 'arrive2':"},
      {c:"            time.sleep(5)#待图像稳定"},
      {c:"            tcpCliSock1.{{send}}(\"getphoto2\".{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:""},
      {c:""},
      {c:"        data = ''  # 清空数据"},
      {c:"        time.sleep(0.5)  # 短暂等待"},
      {c:""},
      {c:"def voice(socket, name):"},
      {c:"    \"\"\"处理语音控制的通信线程函数\"\"\""},
      {c:"    while True:"},
      {c:"        # 接收语音系统发送的数据"},
      {c:"        data = socket.{{recv}}(1024).{{decode}}('utf-8')",tip:"接收数据",why:"recv(1024)收最多1024字节,要.decode转字符串才能比较。"},
      {c:"        print(f\"{name}发送{data}\")"},
      {c:""},
      {c:"        # 如果数据包含方括号（可能是JSON格式或其他格式的语音指令）"},
      {c:"        if \"[\" in str(data):"},
      {c:"            # 检查语音指令内容"},
      {c:"            if \"原点\" in str(data):"},
      {c:"                print(\"执行:回到原点\")"},
      {c:"                # 移动到零点"},
      {c:"                dType.{{SetPTPCmdEx}}(api, 1, P5[0], P5[1], P5[2], P5[3], isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"            elif \"开始\" in str(data):"},
      {c:"                print(\"执行:开始分拣\")"},
      {c:"                # 通知上料系统和分类系统开始运行"},
      {c:"                tcpCliSock2.{{send}}({{\"run\"}}.{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:"                tcpCliSock3.{{send}}({{\"run\"}}.{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:"                # 移动到拍照点"},
      {c:"                dType.{{SetPTPCmdEx}}(api, 1, P1[0], P1[1], P1[2], P1[3], isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"            else:"},
      {c:"                try:"},
      {c:"                    # 从语音指令中提取数字（移动距离）"},
      {c:"                    number = re.findall(r\"\\d+\\.?\\d*\", str(data))[0]"},
      {c:"                    number_float = float(number)"},
      {c:"                    num = number_float * 10  # 转换为毫米"},
      {c:""},
      {c:"                    # 获取当前机械臂位置"},
      {c:"                    Pose = dType.{{GetPose}}(api)"},
      {c:"                    Pose[0] = round(Pose[0], 4)"},
      {c:"                    Pose[1] = round(Pose[1], 4)"},
      {c:"                    Pose[2] = round(Pose[2], 4)"},
      {c:"                    Pose[3] = round(Pose[3], 4)"},
      {c:""},
      {c:"                    # 根据方向指令调整位置"},
      {c:"                    if \"前\" in str(data):"},
      {c:"                        print(f\"执行:机械臂向前移动{number}厘米\")"},
      {c:"                        Pose[0] = Pose[0] + num"},
      {c:"                    elif \"后\" in str(data):"},
      {c:"                        print(f\"执行:机械臂向后移动{number}厘米\")"},
      {c:"                        Pose[0] = Pose[0] - num"},
      {c:"                    elif \"左\" in str(data):"},
      {c:"                        print(f\"执行:机械臂向左移动{number}厘米\")"},
      {c:"                        Pose[1] = Pose[1] + num"},
      {c:"                    elif \"右\" in str(data):"},
      {c:"                        print(f\"执行:机械臂向右移动{number}厘米\")"},
      {c:"                        Pose[1] = Pose[1] - num"},
      {c:"                    elif \"上\" in str(data):"},
      {c:"                        print(f\"执行:机械臂向上移动{number}厘米\")"},
      {c:"                        Pose[2] = Pose[2] + num"},
      {c:"                    elif \"下\" in str(data):"},
      {c:"                        print(f\"执行:机械臂向下移动{number}厘米\")"},
      {c:"                        Pose[2] = Pose[2] - num"},
      {c:""},
      {c:"                    # 移动到新位置"},
      {c:"                    dType.{{SetPTPCmdEx}}(api, 1, Pose[0], Pose[1], Pose[2], Pose[3], isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"                except IndexError:"},
    ]},
    { id:"xl_3", name:"move()抓放函数", lines:[
      {c:"                    print('输入非法,请重试')"},
      {c:""},
      {c:"def move(x, y, z, r, air1, air2, keep):"},
      {c:"    \"\"\""},
      {c:"    机械臂运动控制函数"},
      {c:""},
      {c:"    参数:"},
      {c:"    x, y, z, r: 目标位置坐标"},
      {c:"    air1: 到达目标点前夹爪状态"},
      {c:"    air2: 到达目标点后夹爪状态"},
      {c:"    keep: 是否保持夹爪状态"},
      {c:"    \"\"\""},
      {c:"    # 设置夹爪状态"},
      {c:"    dType.{{SetEndEffectorGripper}}(api, 1, air1, isQueued=1)",tip:"夹爪控制(开/合)",why:"第2参=使能,第3参=开合。现场骨架开头那行常被漏，要补回。"},
      {c:"    # 移动到目标点上方20mm处"},
      {c:"    dType.{{SetPTPCmdEx}}(api, 1, x, y, z + 20, r, isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"    # 下降到目标点"},
      {c:"    dType.{{SetPTPCmdEx}}(api, 1, x, y, z, r, isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"    # 设置夹爪新状态"},
      {c:"    dType.{{SetEndEffectorGripper}}(api, air2, 1, isQueued=1)",tip:"夹爪控制(开/合)",why:"第2参=使能,第3参=开合。现场骨架开头那行常被漏，要补回。"},
      {c:"    dType.{{dSleep}}(1000)  # 等待1秒",tip:"等夹爪夹稳",why:"夹/松爪是机械动作有延迟，不等就抬走会掉料。下料1000ms,上料100ms。"},
      {c:"    # 抬起到目标点上方20mm处"},
      {c:"    dType.{{SetPTPCmdEx}}(api, 1, x, y, z + 20, r, isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"    # 如果不保持夹爪状态，则释放夹爪"},
      {c:"    if keep == 0:"},
    ]},
    { id:"xl_4", name:"TCP服务端主程序", lines:[
      {c:"        dType.{{SetEndEffectorGripper}}(api, 0, air1, isQueued=1)",tip:"夹爪控制(开/合)",why:"第2参=使能,第3参=开合。现场骨架开头那行常被漏，要补回。"},
      {c:""},
      {c:"if __name__ == \"__main__\":"},
      {c:"    # 创建TCP服务器"},
      {c:"    socket_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)  # 建立TCP服务端"},
      {c:"    socket_server.{{bind}}(('127.0.0.1', {{8081}}))  # 绑定IP地址和端口",tip:"绑定IP和端口",why:"下料机当服务器,占住127.0.0.1:8081等别人连。"},
      {c:"    socket_server.{{listen}}(5)  # 最大连接数5",tip:"开始监听",why:"参数5=最多排队5个连接。绑定后必须listen才能accept。"},
      {c:""},
      {c:"    # 连接视觉系统"},
      {c:"    print(\"连接视觉\")"},
      {c:"    tcpCliSock1, ardd1 = socket_server.{{accept}}()  # 阻塞方式连接客户端",tip:"接受客户端连接(阻塞)",why:"按顺序收：视觉→分类→上料。顺序错了对象就连错。返回(连接,地址)。"},
      {c:"    clienThread1 = {{Thread}}(target=vision, args=(tcpCliSock1, \"视觉端\"))  # 创建视觉线程",tip:"创建线程",why:"下料机要同时伺候视觉/分类/上料三方,每个开一条线程并行收发。"},
      {c:"    clienThread1.start()  # 开启线程"},
      {c:"    print(\"连接成功\")"},
      {c:""},
      {c:"    # 连接分类系统"},
      {c:"    print(\"连接分类\")"},
      {c:"    tcpCliSock2, ardd2 = socket_server.{{accept}}()  # 阻塞方式连接客户端",tip:"接受客户端连接(阻塞)",why:"按顺序收：视觉→分类→上料。顺序错了对象就连错。返回(连接,地址)。"},
      {c:"    clienThread2 = {{Thread}}(target=classification, args=(tcpCliSock2, \"分类端\"))  # 创建分类线程",tip:"创建线程",why:"下料机要同时伺候视觉/分类/上料三方,每个开一条线程并行收发。"},
      {c:"    clienThread2.start()  # 开启线程"},
      {c:"    print(\"连接成功\")"},
      {c:""},
      {c:"    # 连接上料系统"},
      {c:"    print(\"连接上料\")"},
      {c:"    tcpCliSock3, ardd3 = socket_server.{{accept}}()  # 阻塞方式连接客户端",tip:"接受客户端连接(阻塞)",why:"按顺序收：视觉→分类→上料。顺序错了对象就连错。返回(连接,地址)。"},
      {c:"    clienThread3 = {{Thread}}(target=load_material, args=(tcpCliSock3, \"上料端\"))  # 创建上料线程",tip:"创建线程",why:"下料机要同时伺候视觉/分类/上料三方,每个开一条线程并行收发。"},
      {c:"    clienThread3.start()  # 开启线程"},
      {c:"    print(\"连接成功\")"},
      {c:""},
      {c:"    # # 连接语音系统"},
      {c:"    # print(\"连接语音\")"},
      {c:"    # tcpCliSock4, ardd4 = socket_server.accept()  # 阻塞方式连接客户端"},
      {c:"    # clienThread4 = Thread(target=voice, args=(tcpCliSock4, \"语音端\"))  # 创建语音线程"},
      {c:"    # clienThread4.start()  # 开启线程"},
      {c:"    # print(\"连接成功\")"},
      {c:""},
      {c:"    # 主循环，等待用户输入"},
      {c:"    while True:"},
      {c:"        temp = input(f\"输入指令:\")"},
      {c:"        # 用户输入任意指令后，启动语音系统"},
      {c:"        dType.{{SetPTPCmdEx}}(api, 1, P1[0], P1[1], P1[2], P1[3], isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"        tcpCliSock3.{{send}}({{\"run\"}}.{{encode}}(\"utf-8\"))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:""},
    ]},
  ],
  run:"连接状态: 已连接\n连接视觉\n连接成功\n连接分类\n连接成功\n连接上料\n连接成功\n输入指令:"
},
{
  name:"上料机器臂/Main.py",
  desc:"TCP客户端·传送带·光电传感器",
  sections:[
    { id:"sl_0", name:"连接初始化", lines:[
      {c:"# 导入必要的库"},
      {c:"from threading import Thread"},
      {c:"import time"},
      {c:"import DobotDllType as dType"},
      {c:"import socket"},
      {c:""},
      {c:"# 加载机械臂动态链接库DobotDll.dll"},
      {c:"api = dType.load()"},
      {c:""},
      {c:"# 连接机械臂"},
      {c:"# ConnectDobot函数返回一个元组，第一个元素是连接状态码"},
      {c:"# 状态码：0-已连接，1-未找到设备，2-端口占用"},
      {c:"# 连接到COM端口，波特率115200"},
      {c:"state = dType.{{ConnectDobot}}(api, {{\"COM16\"}}, {{115200}})[0]",tip:"连接机械臂,取返回元组[0]",why:"返回(状态码,...)，必须带[0]取状态。0=已连接,1=没找到,2=占用。"},
      {c:""},
      {c:"# 打印机械臂连接状态"},
      {c:"# 使用状态码作为索引，从状态描述列表中获取对应文本"},
      {c:"print(\"连接状态:\", [\"已连接\", \"未找到设备\", \"端口占用\"][state])"},
      {c:""},
      {c:"# 设置机械臂PTP运动模式参数(门型运动时抬升高度为100,最大高度为110)"},
      {c:"dType.ClearAllAlarmsState(api)  # 清除所有警报状态"},
      {c:"dType.SetPTPJumpParams(api, 100, 110, isQueued=1)  # 设置跳跃运动参数"},
      {c:"dType.{{SetInfraredSensor}}(api, 1, {{1}}, version=1)  # 设置光电传感器，使能1，端口1",tip:"光电传感器 下料=2 上料=1",why:"第3参是端口号，下料机接2号、上料机接1号，记反了读不到料。"},
      {c:""},
      {c:"# 设置机械臂末端为夹爪"},
      {c:"# 参数：夹爪长度59.7mm，末端类型为夹爪（1表示夹爪）"},
      {c:"dType.SetEndEffectorParams(api, 59.7, 0, 0, 1)"},
      {c:""},
      {c:"# api清空机械臂的指令队列"},
      {c:"dType.SetQueuedCmdClear(api)"},
      {c:""},
      {c:"# 开始执行队列指令"},
      {c:"dType.SetQueuedCmdStartExec(api)"},
      {c:""},
      {c:"# 设置末端夹爪状态：打开夹爪"},
      {c:"# 参数：启用夹爪(1)，夹爪打开(0)"},
      {c:"dType.{{SetEndEffectorGripper}}(api, 0, 0, isQueued=1)",tip:"夹爪控制(开/合)",why:"第2参=使能,第3参=开合。现场骨架开头那行常被漏，要补回。"},
      {c:""},
      {c:"# 设置外部电机（可能是传送带）参数"},
      {c:"# 参数：端口0，使能(0)，速度-10000，是否为队列命令(1)"},
      {c:"dType.{{SetEMotor}}(api, 0, 0, -10000, 1)",tip:"传送带电机",why:"端口0,使能,速度。开头先停(负速)，到位后正转送料。只有上料机有。"},
      {c:""},
      {c:"# 机械臂回零"},
      {c:"dType.SetHOMECmd(api, 1, isQueued=1)"},
    ]},
    { id:"sl_1", name:"坐标与move函数", lines:[
      {c:"#----------------------------------------------------------"},
      {c:""},
      {c:"# 定义关键位置坐标"},
      {c:"P1 = [ 247.0604 , 14.8562 , -70.634 , -76.9556 ]  # 抓取点"},
      {c:"P2 = [-102.2447,-274.7979,30.4728,-169.4937]  # RFID放置点"},
      {c:"P3 = [4.2182,-270.1267,-3.4872,-169.4937]  # 传送带放置点"},
      {c:"P4 = [0, 0]  # 修改（用于存储计算后的坐标）"},
      {c:""},
      {c:"# 初始化码垛位置计数变量"},
      {c:"y = 0"},
      {c:"x = 0"},
      {c:""},
      {c:"def move(x, y, z, r, air1, air2, keep):"},
      {c:"    \"\"\""},
      {c:"    机械臂运动控制函数"},
      {c:""},
      {c:"    参数:"},
      {c:"    x, y, z, r: 目标位置坐标"},
      {c:"    air1: 到达目标点前夹爪状态"},
      {c:"    air2: 到达目标点后夹爪状态"},
      {c:"    keep: 是否保持夹爪状态"},
      {c:"    \"\"\""},
      {c:"    # 设置夹爪状态"},
      {c:"    dType.{{SetEndEffectorGripper}}(api, air1, 1, isQueued=1)",tip:"夹爪控制(开/合)",why:"第2参=使能,第3参=开合。现场骨架开头那行常被漏，要补回。"},
      {c:"    # 移动到目标点上方20mm处"},
      {c:"    dType.{{SetPTPCmdEx}}(api, 1, x, y, z + 50, r, isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"    # 下降到目标点"},
      {c:"    dType.{{SetPTPCmdEx}}(api, 1, x, y, z, r, isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"    # 设置夹爪新状态"},
      {c:"    dType.{{SetEndEffectorGripper}}(api, air2, 1, isQueued=1)",tip:"夹爪控制(开/合)",why:"第2参=使能,第3参=开合。现场骨架开头那行常被漏，要补回。"},
      {c:"    dType.{{dSleep}}(100)  # 等待0.1秒",tip:"等夹爪夹稳",why:"夹/松爪是机械动作有延迟，不等就抬走会掉料。下料1000ms,上料100ms。"},
      {c:"    # 抬起到目标点上方20mm处"},
      {c:"    dType.{{SetPTPCmdEx}}(api, 1, x, y, z + 50, r, isQueued=1)",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:"    # 如果不保持夹爪状态，则释放夹爪"},
      {c:"    if keep == 0:"},
    ]},
    { id:"sl_2", name:"TCP客户端主程序", lines:[
      {c:"        dType.{{SetEndEffectorGripper}}(api, 0, 0, isQueued=1)",tip:"夹爪控制(开/合)",why:"第2参=使能,第3参=开合。现场骨架开头那行常被漏，要补回。"},
      {c:""},
      {c:""},
      {c:"if __name__ == \"__main__\":"},
      {c:"    # 创建TCP客户端套接字"},
      {c:"    socket_client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)  # 建立客户端"},
      {c:""},
      {c:"    socket_client.{{connect}}((\"127.0.0.1\", {{8081}}))  # 与服务器建立连接",tip:"连接服务端8081",why:"上料/分类是客户端,主动连下料机的8081。"},
      {c:"    print('连接成功')"},
      {c:""},
      {c:"    # 主循环"},
      {c:"    while True:"},
      {c:"        data=''#清空数据"},
      {c:"        # 等待接收服务器发送的数据，最大1024字节，解码为UTF-8格式"},
      {c:"        data = socket_client.{{recv}}(1024).{{decode}}('utf-8')",tip:"接收数据",why:"recv(1024)收最多1024字节,要.decode转字符串才能比较。"},
      {c:"        print(data)  # 打印接收到的数据"},
      {c:"        # 如果接收到的数据不是'run'字符串，跳过本次循环"},
      {c:"        if data != 'run':"},
      {c:"            continue"},
      {c:""},
      {c:"        # 码垛算法，计算抓取点的X、Y坐标"},
      {c:"        # 根据x、y值计算偏移后的抓取位置"},
      {c:"        P4[1] = (P1[1] - (y * 50))  # 计算Y坐标：每增加y值，Y坐标减少50mm"},
      {c:"        P4[0] = (P1[0] - (x * 50))  # 计算X坐标：每增加x值，X坐标减少50mm"},
      {c:""},
      {c:"        # 更新y值（列计数器）"},
      {c:"        if y < 3:  # 如果y小于3，y加1"},
      {c:"            y += 1"},
      {c:"        else:  # 如果y等于3，重置y为0，x加1（换行）"},
      {c:"            y = 0"},
      {c:"            x = 1  # 注意：这里x只会在y达到3时设置为1，之后不会增加"},
      {c:""},
      {c:"        move(P4[0], P4[1], P1[2], P1[3], 0, 1, 1)#码垛抓取"},
      {c:""},
      {c:"        move(P2[0], P2[1], P2[2], P2[3], 1, 0, 0)#RFID放下"},
      {c:""},
      {c:"        dType.{{SetPTPCmdEx}}(api, 1, P3[0], P3[1], P2[2] + 60, P2[3], isQueued=1)#拍照回避",tip:"PTP点到点运动",why:"第2参=1是运动模式,后面x,y,z,r坐标。带Ex是阻塞版,执行完才返回。"},
      {c:""},
      {c:"        socket_client.{{send}}({{\"arrive1\"}}.{{encode}}('utf-8'))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:""},
      {c:""},
      {c:""},
      {c:"        while('OK' not in data):"},
      {c:"            data=''#清空数据"},
      {c:"            # 等待接收服务器发送的数据，最大1024字节，解码为UTF-8格式"},
      {c:"            data = socket_client.{{recv}}(1024).{{decode}}('utf-8')",tip:"接收数据",why:"recv(1024)收最多1024字节,要.decode转字符串才能比较。"},
      {c:"            print(data)  # 打印接收到的数据"},
      {c:"            time.sleep(0.5)"},
      {c:""},
      {c:"        move(P2[0], P2[1], P2[2], P2[3], 0, 1, 1)#RFID抓取"},
      {c:""},
      {c:"        move(P3[0], P3[1], P3[2], P3[3], 1, 0, 0)#传送带放下"},
      {c:"        # 启动传送带"},
      {c:"        # 参数：端口0，使能(1)，速度10000，是否为队列命令(1)"},
      {c:"        dType.{{SetEMotor}}(api, 0, 1, 10000, 1)",tip:"传送带电机",why:"端口0,使能,速度。开头先停(负速)，到位后正转送料。只有上料机有。"},
      {c:""},
      {c:"        # 循环检测光电传感器状态"},
      {c:"        while True:"},
      {c:"            i = [0]  # 初始化传感器状态变量"},
      {c:"            i = dType.{{GetInfraredSensor}}(api, 1)  # 读取光电传感器（端口1）状态",tip:"读光电传感器",why:"返回列表,i[0]==1表示挡光=料到位。靠它判断传送带送到没。"},
      {c:"            if i[0] == 1:  # 如果传感器检测到高电平（有物体）"},
      {c:"                break  # 跳出检测循环"},
      {c:"         # 停止传送带"},
      {c:"        dType.{{SetEMotor}}(api, 0, 0, -10000, 1)",tip:"传送带电机",why:"端口0,使能,速度。开头先停(负速)，到位后正转送料。只有上料机有。"},
      {c:"        # 给下料系统发送到位信号"},
      {c:"        socket_client.{{send}}({{\"arrive2\"}}.{{encode}}('utf-8'))",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:""},
      {c:""},
    ]},
  ],
  run:"连接成功\nrun\n>>> 取料→RFID→传送带→arrive2 一轮完成"
},
{
  name:"深度学习分类/main.py",
  desc:"ResNet18识别·读RFID·发种类",
  sections:[
    { id:"cls_0", name:"识别主程序", lines:[
      {c:"# 导入必要的模块"},
      {c:"from ResNet import predict  # 从ResNet模块导入预测函数"},
      {c:"from ResNet import showResult  # 从ResNet模块导入结果显示函数"},
      {c:"from ResNet import remove_result  # 从ResNet模块导入结果清除函数"},
      {c:"from read_card_text import get_decoded_text  # 从read_card_text模块导入文本解码函数"},
      {c:""},
      {c:"import cv2  # OpenCV库，用于图像处理"},
      {c:"import socket  # 网络通信库"},
      {c:"import time  # 时间处理库"},
      {c:""},
      {c:""},
      {c:""},
      {c:"def main():"},
      {c:"    \"\"\"主函数，负责与服务器建立连接并处理分类任务\"\"\""},
      {c:""},
      {c:"    # 创建TCP客户端套接字"},
      {c:"    socket_client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)"},
      {c:""},
      {c:"    try:"},
      {c:"        # 尝试连接到本地主机的8081端口"},
      {c:"        socket_client.{{connect}}((\"127.0.0.1\", {{8081}}))",tip:"连接服务端8081",why:"上料/分类是客户端,主动连下料机的8081。"},
      {c:"        print('连接成功')"},
      {c:"    except Exception as e:"},
      {c:"        # 连接失败时打印异常信息"},
      {c:"        print(e)"},
      {c:""},
      {c:"    # 清空结果图片（防止之前的结果影响当前识别）"},
      {c:"    remove_result()"},
      {c:""},
      {c:""},
      {c:"    while True:"},
      {c:"        try:"},
      {c:"            # 接收服务器发送的数据"},
      {c:"            data = socket_client.{{recv}}(1024).{{decode}}('utf-8')",tip:"接收数据",why:"recv(1024)收最多1024字节,要.decode转字符串才能比较。"},
      {c:"            print(data)"},
      {c:""},
      {c:"            # 定义图片路径"},
      {c:"            imagePath = \"./img.bmp\""},
      {c:""},
      {c:"            # 检查数据中是否包含\"M\""},
      {c:"            if \"M\" in data:",tip:"编号标志",why:"视觉识别出二维码后发以M开头的编号,分类端收到才开始识别。"},
      {c:"                print(f\"开始识别\")"},
      {c:""},
      {c:"                # 使用OpenCV读取图片"},
      {c:"                img = cv2.imread(imagePath)"},
      {c:""},
      {c:"                # 调用预测函数对图片进行分类识别"},
      {c:"                result = {{predict}}(img)",tip:"ResNet18识别",why:"返回(种类,编号,置信度)。本赛用深度学习分类,不是OpenCV形状识别。"},
      {c:""},
      {c:"                # 如果结果为0（可能是预测失败），跳过本次循环"},
      {c:"                if result == 0:"},
      {c:"                    continue"},
      {c:""},
      {c:"                # 打印识别结果"},
      {c:"                # result[0]: 物品类别"},
      {c:"                # result[1]: 编号"},
      {c:"                # result[2]: 置信度"},
      {c:"                print(f\"结果:{result[0]},编号:{result[1]},置信度:{result[2]}\")"},
      {c:""},
      {c:"                # 调用文本解码函数获取编码信息"},
      {c:"                code = {{get_decoded_text}}()",tip:"读RFID文本",why:"读card_result.json里RFID解出的\"省份;时间\"。现场缺此文件要从RFID64bit拷。"},
      {c:""},
      {c:"                # 处理解码结果"},
      {c:"                if code:"},
      {c:"                    print(f\"解码文本: {code}\")"},
      {c:"                    # 编码格式为\"产地;时间\"，分割字符串"},
      {c:"                    sp_code1 = str(code).{{split}}(\";\")[0]  # 产地信息",tip:"按分号分割",why:"RFID内容格式是\"省份;时间\",split(\";\")[0]取省份,[1]取时间。"},
      {c:"                    sp_code2 = str(code).{{split}}(\";\")[1]  # 时间信息",tip:"按分号分割",why:"RFID内容格式是\"省份;时间\",split(\";\")[0]取省份,[1]取时间。"},
      {c:"                else:"},
      {c:"                    print(\"无解码文本或文件不存在\")"},
      {c:""},
      {c:"                # 格式化显示文本"},
      {c:"                text1 = (f\"种类:{result[{{0}}]}\")  # 物品种类"},
      {c:"                text2 = (f\"编号:{data}\")  # 接收到的编号"},
      {c:"                text3 = (f\"产地:{sp_code1}\")  # 产地"},
      {c:"                text4 = (f\"时间:{sp_code2}\")  # 时间"},
      {c:""},
      {c:"                # 向下料机发送分类依据"},
      {c:"                socket_client.{{send}}(result[{{0}}].{{encode}}(\"utf-8\"))  # 发送种类",tip:"发送数据",why:"发送的必须是bytes,所以要\"xxx\".encode(\"utf-8\")。漏encode直接报错。"},
      {c:"                # socket_client.send(sp_code1.encode(\"utf-8\"))  # 发送产地"},
      {c:"                # socket_client.send(sp_code2.encode(\"utf-8\"))  # 发送时间"},
      {c:""},
      {c:"                # 显示结果弹窗，持续5000毫秒（5秒）"},
      {c:"                showResult(img, 5000, text1, text2, text3, text4)"},
      {c:""},
      {c:""},
      {c:"        except UnicodeDecodeError:"},
      {c:"            # 处理解码异常"},
      {c:"            print('error')"},
      {c:"            time.sleep(0.1)  # 等待0.1秒后重试"},
      {c:""},
      {c:""},
      {c:"if __name__ == \"__main__\":"},
      {c:"    # 程序入口点"},
      {c:"    main()"},
      {c:""},
      {c:"    # 以下是被注释的测试代码："},
      {c:"    # img = cv2.imread(\"./img.bmp\")"},
      {c:"    # result = predict(img)"},
      {c:"    # print(result)"},
    ]},
  ],
  run:"连接成功\nMxxxx\n开始识别\n结果:1.jqr,编号:Mxxxx,置信度:0.98"
}
];
